name: 'Bump Version Package Json'
description: 'Action to automatically change the version in package.json with the value on tag'
inputs:
  tag:
    description: 'Tag created'
    required: true
    default: 'v1.0.0'
  commit:
    description: 'commit the change on package.json'
    required: false
    default: 'false'
  branch_to_push:
    description: 'branch to push on git'
    required: false
    default: 'main'
  path:
    description: 'path to package.json'
    required: false
    default: './package.json'
outputs:
  parsed-tag:
    description: 'The tag parsed'
runs:
  using: 'node16'
  main: 'index.js'
